---
- name: AddLineAndREgistry - TEST
  hosts: all

  tasks:

  #- name: Hello World! {{ my_variable }}
  #  shell: echo "Hi! Tower is working! v2 My variable {{ my_variable }}"

  - name: Add line to file
    lineinfile:
      path: C:\temp\MyFile.txt
      line: |
        This is my text
        ""
      insertafter: EOF
        
  - name: Add or update registry path MyCompany, with dword entry 'hello', and containing 0xff2500ae as the hex value
    win_regedit:
      path: HKCU:\Software\MyCompany
      name: hello
      data: 0xff2500ae
      type: dword
