---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World! {{ my_variable }}
    shell: echo "Hi! Tower is working! v2 My variable':' '{{ my_variable }}'"

  - name: Add line to file
    lineinfile:
        path: "/tmp/MyTest/MyFile.txt"
        line: |
            "XXX Host {{ ansible_hostname }}"
            "{{ stuff.stdout }}"
            ""
            ""
        insertafter: EOF
        
  - name: Add or update registry path MyCompany, with dword entry 'hello', and containing 0xff2500ae as the hex value
    win_regedit:
        path: HKCU:\Software\MyCompany
        name: hello
        data: 0xff2500ae
        type: dword
        
# delegate_to: 127.0.0.1

#  - name: Creates directory
#    file:
#      path: /tmp/MyTest
#      state: directory
      
      
#  - name: Encription status...
#    debug: msg="I created this debug message '{{ my_variable }}'"
