---
- name: AddLineAndREgistry - TEST
  hosts: all
  gather_facts: yes
  tasks:

  - name: Hello World! {{ my_variable }}
    win_shell: echo "Hi! '{{ my_variable }}'"

  - name: Create file if it doesn't exist with a specific encoding
    win_lineinfile:
      path: C:\temp\utf16.txt
      create: yes
      encoding: utf-16
      line: This is a utf-16 encoded file

  - name: Add line to file test
    win_lineinfile:
      path: C:\temp\utf16.txt
      line: |
        This is my text
        ""
      insertafter: EOF
        
  # HKCU means HKEY_CURRENT_USER
  - name: Add or update registry path MyCompany, with dword entry 'hello', and containing 0xff2500ae as the hex value
    win_regedit:
      path: HKCU:\Software\MyCompany
      name: hello
      data: 0xff2500ae
      type: dword
