---
# tasks file for was-status-handler

- name: connection checker
  hosts: all
  ignore_errors: true
    
  tasks:

    - name: "WAS Status Windows Handler"
      include_tasks: windows.yml
      when: ansible_facts['os_family'] == "Windows"
