- name: Copy file from remote to local Windows server
  hosts: local_server
  gather_facts: no
  tasks:
    - name: Copy file
      win_copy:
        src: "\\172.16.25.22\C$\qakreport.zip"
        dest: "C:\temp\qakreport.zip"
      vars:
        ansible_user: "{{ username }}"
        ansible_password: "{{ password }}"
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
