---
- name: Copy file playbook
  hosts: all

  tasks:
  
  - name: Copy file
    copy:
      src: ./Files/TestFile.txt 
      dest: \\{{ inventory_hostname }}\c$\TestFile.txt
    delegate_to: localhost
