- name: Copy file from remote to local Windows server
  hosts: all
  gather_facts: yes
  tasks:
    - name: Copy file
      win_copy:
        src: \\172.16.25.22\C$\qakreport.zip
        remote_src: yes
        dest: C:\temp\qakreport.zip
      vars:
        ansible_user: Training
        ansible_password: Training1!
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
