---
- name: Fetch test
  hosts: all
  gather_facts: yes
  tasks:
  
    - name: Copy file from playbook
      win_copy:
        src: TestZip.zip
        dest: c:\temp\TestFile.txt
      #delegate_to: localhost
  
    - name: Unzip a bz2 (BZip) file
      win_unzip:
        src: C:\Users\Phil\Logs.bz2
        dest: C:\Users\Phil\OldLogs
  
    - name: Fetch file from remote host
      fetch:
        src: c:\Windows\System32\Drivers\etc\hosts
        dest: /tmp/
           
    - name: Display file contents
      debug: var=item
      with_file:
        - "/tmp/172.16.25.23/c:/Windows/System32/Drivers/etc/hosts"  
  
    - name: Copy file
      win_copy:
        src: TestFile.txt
        dest: c:\temp\TestFile.txt
      #delegate_to: localhost
