---
- name: Copy file playbook
  hosts: all

  tasks:
  
  - name: Copy file
    copy:
      src: ./TestFile.txt 
      dest: \\{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\c$\TestFile.txt
    delegate_to: localhost
