---
- name: Copy file playbook
  hosts: all

  tasks:
  
  - name: Print working directory
    win_shell: pwd
  
  - name: Copy file
    win_copy:
      src: TestFile.txt
      dest: c:\temp\TestFile.txt
    #delegate_to: localhost
