---
- name: Use encryption key
  hosts: all

  tasks:

  - name: Use custom credential value
    debug:
      var: "{{ encryption_key_new }}"
      
  - name: Try to write it
    debug:
      msg: This is the key {{ encryption_key_new }}
      

  - name: Use custom credential value added to group
    debug:
      var: "{{ encryption_key_added_to_group }}"
      
  - name: Use custom credential value added to group
    debug:
      msg: This is the key {{ encryption_key_added_to_group }}
