---
- name: Fetch test
  hosts: all
  gather_facts: yes
  tasks:
    - name: Fetch file from remote host
      fetch:
        src: c:\Windows\System32\Drivers\etc\hosts
        dest: /tmp/
           
    - name: Display file contents
      debug: var=item
      with_file:
        - "/tmp/172.16.25.23/c:/Windows/System32/Drivers/etc/hosts"
