---
- name: Get custom credential
  hosts: all

  tasks:
  
  - name: Retrieve value from custom credential
    tower_get_credentials:
      credential_type: "Custom Credential"
      name: "My Custom Credential"
    register: custom_credential

  - name: Use custom credential value
    debug:
      var: custom_credential
