---
- name: Install file windows
  hosts: all

  tasks:
  
  - name: Unzip (old versions)
    win_shell: |
      $file = $([string]$pwd + "\LMT-DisconnectedScanner-windows-9.2.30.0-20221206-1315.zip") 
      $destination = $pwd
      
      $shell = new-object -com shell.application
      $zip = $shell.NameSpace($file)
      foreach($item in $zip.items())
      { 
        $shell.Namespace($destination).copyhere($item)
      }
  
  - name: Run bach file
    win_shell: [string]$pwd + "\MyBatch.bat"
