
---
- name: Interpolation test
  hosts: all
  vars:
    text1: This is a single line "

  tasks:
        
  - name: "{{ text1 | regex_replace('a', 'AA')  }}"
    shell: echo "{{ text1 }}"
        
  - name: "{{ text1 | regex_replace('\"', '\"\"')  }}"
    shell: echo "{{ text1 | regex_replace('\"', '\"\"') }}"
