---
- name: Hello World!
  hosts: all

  vars:
    # This could be the service you are checking
    numbers:
    - Stable
    - Not stable

  tasks:
    # This would get the status of the service
    - name: Register loop output as a variable
      win_shell: echo "{{ item }}"
      loop: "{{ numbers }}"
      register: echo
 
    # You could loop through the results from above and if it contains the value Stable, do something
    # The list item you are looking at is called "item"
    - block:
 
      - name: Loop through code
        include_tasks: LoopTask.yml
 
      loop: "{{ echo.results }}"
