---
- name: Hello World!
  hosts: all

  vars:
    numbers:
    - One
    - Two

  tasks:
    - name: Register loop output as a variable
      win_shell: echo "{{ item }}"
      loop: "{{ numbers }}"
      register: echo
      
    - name: Print output
      debug:
        msg: "Result from command above: {{ item.stdout }}"
      loop: "{{ echo.results }}"
