---
- name: Hello World!
  hosts: all

  tasks:
    - name: Register loop output as a variable
      win_shell: echo "{{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
      
    - name: Print output
      debug:
        msg: "Result from command above {{ item }}"
      loop: "{{ echo.results }}"
