---
- name: Password
  hosts: all

  tasks:
  
    # This would get the status of the service. It goes the the list windows_service
    - name: Show all environment variables
      win_shell: dir env:
