---
- name: Text test playbook
  hosts: all
  vars:
    text1: This is a single line

  tasks:

  # Ping the server attempt 1
  - name: ping test
    shell: ping -c 1 -w 2 {{ ansible_host }}
    delegate_to: localhost
    ignore_errors: true
    register: ping_result_1
    
  # Ping the server attempt 2 if attempt 2 doesnt work
  - name: ping test
    shell: ping -c 1 -w 2 {{ ansible_host }}
    delegate_to: localhost
    ignore_errors: true
    register: ping_result_2
    #when: '"value" in ping_result_1'
    #when: '"value" not in ping_result_1'
    
  # If both pings fail return the code to escalate the alert to a human  
  - name: Failed - return rc code to ensure ticket is escalated
    
    
  # When either ping has worked run this block of code
  - name: Check if agent is running and responding to 
    block:
    - name: Install httpd and memcached

     when: ansible_facts['distribution'] == 'CentOS'
     ignore_errors: yes
 
    
