---
- name: Hello World!
  hosts: all

  tasks:

  - name: Read write text file test
    block:

      - name: Create Directory
        file:
          path: /tmp/MyTest
          state: directory
        delegate_to: 127.0.0.1
        run_once: true

      - name: Creating an empty file
        file:
          path: "/tmp/MyTest/MyFile.txt"
          state: touch
        run_once: true

      #- name: Copy text to file
      #  copy:
      #    content: "This is my text that i copied"
      #    dest: "/tmp/MyTest/MyFile.txt"
          
      - name: Copy line of text to file
        lineinfile:
          path: "/tmp/MyTest/MyFile.txt"
          line: "This is my text that i copied {{ ansible_system }} "
          #create: no
          insertafter: EOF
          
      - name: Read file to fact
        set_fact:
          file_text: "{{ lookup('file', '/tmp/MyTest/MyFile.txt') }}"
        run_once: true
        
      - name: Show content from file
        debug: msg="The text from file- '{{ file_text }}'"
        when: inventory_hostname != ansible_play_hosts_all[-1]
        # https://devops.stackexchange.com/questions/6058/can-i-check-whether-ansible-is-on-last-batch-of-rolling-update-serial-25
        run_once: true

    delegate_to: 127.0.0.1
