---
- name: Run PowerShell Command Every Minute
  hosts: all
  gather_facts: false

  tasks:
      
    - name: Set Default Value
      win_shell: Write-Host "5"
      register: loopCount
      
    - name: Run command until it returns "FALSE"
      win_shell: Write-Host "FALSE"
      register: value_normal
      loop: "{{ range(loopCount.stdout | int) | list }}"
      delay: 10
      when: value_normal.stdout | default('FALSE') == 'FALSE'
