---
- name: Run PowerShell Command Every Minute
  hosts: all
  gather_facts: false

  tasks:
      
    - name: Loop with Break
      win_shell: Write-Host "FALSE"
      register: value_normal
      loop: "{{ range(5) | list }}"
      delay: 10
      when: value_normal.stdout | default('FALSE') == 'FALSE'
