- name: Playbook name
  hosts: all

  tasks:
  - name: Check for foldeer
    shell: ping -c 60 8.8.8.8
    delegate_to: 127.0.0.1
    run_once: true
    become: yes
    become_method: su
    become_password: Training1!
    
  - name: Write folder exists
    debug:
      msg: "Finished ping"
