- name: Playbook name
  hosts: all

  tasks:
  - name: Check for foldeer
    shell: ping -t 60 8.8.8.8
    delegate_to: 127.0.0.1
    run_once: true
    
  - name: Write folder exists
    debug:
      msg: "Finished ping"
