- name: Playbook name
  hosts: all

  tasks:
  - name: Check for foldeer
    stat:
      path: /Ansible123/
    register: register_name
    delegate_to: 127.0.0.1
    run_once: true
    
  - name: Write folder exists
    debug:
      msg: "The file or directory exists"
    when: register_name.stat.exists
