- name: Playbook name
  hosts: all

  tasks:
  - name: Check for foldeer
    shell: ps aux | grep ping
    delegate_to: 127.0.0.1
    run_once: true
    
  - name: Write folder exists
    debug:
      msg: "Checked for ping"
