---
- name: Text test playbook
  hosts: all
  vars:
    text1: This is a single line
  tasks:

  - name: Hello World! {{ text1 }}
    win_shell: echo "Text1"
    
- name: GetFactsDemo
  hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: Version
    debug: msg="{{ ansible_distribution }}"
