---
- name: Test when 
  hosts: all

  tasks:
  
    # Run the windows command to add to the text file. If the file already exists, no action is taken
    - name: Run the windows command to add the entry to the text file
      win_shell: Write-Host "True"
      register: add_line_output

    # Run the windows command to add to the text file. If the file already exists, no action is taken
    - name: Show debug that the line exists in config file
      debug:
        msg: "Config contains line"
      when: "'True' in add_line_output.stdout | default('')"
