---
- name: Text test playbook
  hosts: all
  tasks:
  
  - name: Hello World!
    win_shell: sc queryex Winmgmt
    register: my_variable
    
  - name: Version
    debug: msg="{{ my_variable.stdout }}"
    
  - name: Version
    debug: msg="{{ my_variable }}"
    
- name: GetFactsDemo
  hosts: all
  gather_facts: yes
  become: false
  
  
  tasks:
  - name: Version
    debug: msg="{{ my_variable.stdout }}"
  - name: whoami
    debug: msg="{{ my_variable.stdout }}"
  
  # how to get the serives 
  #Get-Service 
