---
- name: Text test playbook
  hosts: all
  vars:
    text1: >
      This is the first line
      This is the second line
      This is the third line
    text2: |
      This is the first line
      This is the second line
      This is the third line
    text3: "Antidisestab\n
      lishmentarianism.\n\nGet on it."

  tasks:

  - name: Hello World! {{ my_variable }}
    shell: echo "Hi! Tower is working! v2 My variable':' '{{ my_variable }}'"

  - name: Creates directory
    file:
      path: /tmp/MyTest
      state: directory
      
      
  - name: Encription status...
    debug: msg="I created this debug message '{{ my_variable }}'"
