---
- name: Text test playbook
  hosts: all
  vars:
    text1: >
      This is the first line
      This is the second line
      This is the third line
    text2: |
      This is the first line
      This is the second line
      This is the third line
    text3: "Antidisestab\nlishmentarianism.\n\nGet on it."
    text4: |-
        Antidisestab
           lishmentarianism.
        lishmentarianism.   

  tasks:

  - name: Hello World! {{ text1 }}
    shell: echo "Text1"
    
  - name: Hello World! {{ text2 }}
    shell: echo "Text1"
    
  - name: Hello World! {{ text3 }}
    shell: echo "Text1"
    
  - name: Hello World! {{ text4 }}
    shell: echo "Text1"

