---
- name: Show value of whoami v2
  hosts: all
  tasks:
    - name: Check my user name
      ansible.windows.win_whoami:
      register: who_am_i_response
  # - debug: var=who_am_i_response.stdout


#    - name: Create variable from command
#      command: "echo Hello"
#      register: command_output
#    - debug: msg="{{command_output.stdout}}"
