---
- name: Show value of whoami v2
  hosts: all
  tasks:
    - name: Save the result of 'whoami' in 'whoami_out'
      win_command: whoami
      register: whoami_out
   
    - name: Print version
      debug:
        msg: "Ansible Version: {{ whoami_out.stdout }}"
   

#    - name: Create variable from command
#      command: "echo Hello"
#      register: command_output
#    - debug: msg="{{command_output.stdout}}"
