
---
- name: Service Checker
  hosts: all
  #collections:
  #  - ansible.windows

  gather_facts: true

  tasks:

  - name: Restart a service
    win_service:
      name: spooler
      state: restarted
      
  - name: Check if a service is installed
    win_service:
      name: service name
    register: service_info
