
---
- name: Service Checker
  hosts: all
  #collections:
  #  - ansible.windows

  gather_facts: true

  tasks:

  - name: Restart a service
    win_service:
      name: spooler
      state: restarted
      
  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      var: ansible_facts.services
