---
- name: Show value of whoami v2
  hosts: all
  vars:
    service_to_check:
      - Network
      - Remote
 
  tasks:
    - name: load each db
      include_tasks: "create_db_each.yml"
      loop: "{{ service_to_check }}"
