---
- name: Check the services
  hosts: all
  vars:
    service_to_check:
      - Network
      - Remote
 
  tasks:
    - name: Set facts
      set_facts:
        results: []
  
    - name: Go through each service
      include_tasks: "WinServicesCheck_LoopedTasks.yml"
      loop: "{{ service_to_check }}"
